name: TCATemplate
options:
  deploymentTarget:
    iOS: "18.0"
  developmentLanguage: ja
  fileTypes:
    icon:
      file: true # IconComposer
settings:
  base:
    SWIFT_VERSION: 6.0
packages:
  iOS:
    path: ../iOS
targets:
  TCATemplate:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: TCATemplate
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.TCATemplate
        TARGETED_DEVICE_FAMILY: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
    dependencies:
      - package: iOS
        product: AppFeature
schemes:
  TCATemplate:
    build:
      targets:
        TCATemplate: all
    run:
      config: Debug
    archive:
      config: Release
